apiVersion: v1
kind: ServiceAccount
metadata:
  name: account-cluster-manager-xavpf
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: role-cluster-manager-xavpf
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["chaos-mesh.org"]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bind-cluster-manager-xavpf
subjects:
- kind: ServiceAccount
  name: account-cluster-manager-xavpf
  namespace: default
roleRef:
  kind: ClusterRole
  name: role-cluster-manager-xavpf
  apiGroup: rbac.authorization.k8s.io

