apiVersion: v1
kind: Service
metadata:
  name: chaos-dashboard-lb
  namespace: chaos-testing
  annotations:
    meta.helm.sh/release-name: chaos-mesh
    meta.helm.sh/release-namespace: chaos-testing
    prometheus.io/port: "2334"
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/component: chaos-dashboard
    app.kubernetes.io/instance: chaos-mesh
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: chaos-mesh
    app.kubernetes.io/part-of: chaos-mesh
    app.kubernetes.io/version: 2.8.0
    helm.sh/chart: chaos-mesh-2.8.0
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
  - name: metric
    port: 80
    targetPort: 2333
    protocol: TCP
  selector:
    app.kubernetes.io/component: chaos-dashboard
    app.kubernetes.io/instance: chaos-mesh
    app.kubernetes.io/name: chaos-mesh

